// The app's version name, shown at the top right of the navigation bar.
//
// Generated by scripts/android-version.mjs from android/version.properties
// (the single place the version is bumped) - do not edit by hand. Run
// `npm run android:version` to bring this file back in line.
export const APP_VERSION = '1.0.7';
